### ISSUE TITLE
Related work for paper review

### ISSUE THREAD

**Issue by SamTov** [sisl/PyroRL#13]
The one thing missing for me is the related work. I did a very short search for RL and wildfire evacuation strategies and found a few papers:

* https://link.springer.com/article/10.1007/s10694-023-01363-1
* https://www.climatechange.ai/papers/neurips2021/22
* https://www.sciencedirect.com/science/article/abs/pii/S0378437121001175
* https://pubs.aip.org/aip/acp/article/3078/1/040005/3284720/A-reinforcement-learning-algorithm-for-the-optimal

and software

* https://github.com/elbecerrasoto/gym-forest-fire

I understand that these are  a bit different to what you have done but I guess it should be mentioned somewhere in the paper as it is a specific requirement in the JOSS guidelines.

**Comment by cpondoc** [comment]
Hey @SamTov -- sounds good! I believe we should've already looked at the repo, but will take a look and write up a paragraph or two about the related work. Thanks again for the ping!

**Comment by mikemahoney218** [comment]
https://github.com/openjournals/joss-reviews/issues/6739 (just commenting so these get linked :smile: )

**Comment by joey-obrien** [comment]
Hey @SamTov - thanks for the feedback! We reworked the related work in the Statement of Need to include four of the five references you listed above alongside more references to work done on wildfire evacuation and work that used RL for evacuation.

**Comment by SamTov** [comment]
Looks good on my side, thanks for the additional work!
